#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jan 26 23:40:38 2019

@author: jtran
"""

import sys
from lyft_analysis.db import redshift3 as rs3
from lyft_analysis.db import redshift as rs1
import os
import pandas as pd
from lyft_analysis import credentials

sql_statement_type = sys.argv[1]
csv_filepath = sys.argv[2]
table_path = sys.argv[3]
dbt = rs3.DatabaseTool()

# df = pd.read_csv(csv_filepath, skip_blank_lines = True)
df = pd.read_csv('/Users/jtran/Documents/rate_card.csv', low_memory=False, parse_dates = True, skip_blank_lines = True)
dbt._to_sql_via_file(df, table_path)


df = rs3.query('~/Downloads/TEST.csv')

credentials._build_db_credentials(presto)

from lyft_analysis import credentials
print(credentials._DATABASE_CONFIG)

os.environ.get('LYFT_USERNAME')